@startuml containers
!include <C4/C4_Container>

Person(user, "Пользователь")

System_Boundary(WarmHouse, "WarmHouse") {
    Container(apiGateway, "API Gateway", "", "Единая точка входа")
    Container(temperatureApi, "Temperature API", "", "Рандомизирует данные о температуре")
    Container(MonitoringService, "Monitoring Service", "", "Собирает, хранит, предоставляет данные о телеметрии")
    Container(deviceService, "Device Service", "", "Управляет устройствами")
}

ContainerDb(database, "DataBase PostgreSQL", "", "База данных для хранения информации о датчиках и данных о температуре")
System_Ext(Sensors, "Temperature Sensors", "Датчики температуры в доме")

Rel(user, apiGateway, "Просматривает данные, управляет системой",)
Rel(apiGateway, MonitoringService, "Получает данные мониторинга")
Rel(apiGateway, deviceService, "Управляет устройствами")
Rel(apiGateway, temperatureApi, "Запрашивает температуру")
Rel(temperatureApi, Sensors, "Получает данные от датчиков")
Rel(deviceService, database, "Читает/пишет устройства")
Rel(MonitoringService, database, "Читает/пишет телеметрию")
Rel(MonitoringService, temperatureApi, "Запрашивает показания")



@enduml