@startuml components-device
!include <C4/C4_Component>

' Попытка в стилизацию
skinparam {
    backgroundColor #FAFAFA
    roundCorner 10
    shadowing true
    wrapWidth 200
}

Container(Monolit, Монолит, "", "API Gateway")
ContainerDb(database, "PostgreSQL", "База данных")

Container_Boundary(deviceService, "Device Service") {
    Component(commandEndpoints, "Command Endpoints", "", "Управление командами устройств")
    Component(deviceEndpoints, "Device Endpoints", "", "Операции для устройств")
    Component(deviceContext, "Device Context", "", "Для работы с БД")
}

Rel(Monolit, deviceEndpoints, "GET /api/devices, POST /api/devices")
Rel(Monolit, commandEndpoints, "POST /api/commands, GET /api/commands/status")
Rel(deviceEndpoints, deviceContext, "")
Rel(commandEndpoints, deviceContext, "Сохраняет или получает команды")
Rel(deviceContext, database, "SQL-запрос")

@enduml