@startuml
!include <C4/C4_Component>

' Попытка в стилизацию
skinparam {
    backgroundColor #FAFAFA
    roundCorner 20
    shadowing true
    wrapWidth 400
}

Container_Boundary(monitoringService, "monitoring Service") {
    Component(monitoringEndpoints, "Monitoring Endpoints", "", "Эндпоинты для работы с мониторингом")
    Component(monitoringContext, "monitoring Context", "", "Для работы с БД")
    Component(sensorEndpoints, "Sensor Endpoints", "", "Эндпоинты для работы с датчиками")
    }

Container(Monolit, Монолит, "", "API Gateway")
Container(temperatureApi, "Temperature API", "", "Датчики")
ContainerDb(database, "PostgreSQL", "База данных")

Rel(Monolit, monitoringEndpoints, "POST /api/monitoring, GET /api/monitoring/latest")
Rel(Monolit, sensorEndpoints, "GET /api/sensors")
Rel(monitoringEndpoints, monitoringContext, "Получает, хранит и предоставляет данные")
Rel(sensorEndpoints, monitoringContext, "Получает датчики")
Rel(monitoringContext, database, "SQL запросы")
Rel(monitoringEndpoints, temperatureApi, "Запрашивает показания")

@enduml